### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by crazyhottommy** [nservant/HiC-Pro#103]
Hi, 

How can I fix the error below?

thanks!
installing the most recent version.

```
make install
(g++ -Wall -O2 -std=c++0x -o build_matrix /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts/src/build_matrix.cpp; mv build_matrix /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts)
(g++ -Wall -O2 -std=c++0x -o cutsite_trimming /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts/src/cutsite_trimming.cpp; mv cutsite_trimming /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts)
(cp /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts/src/ice_mod/iced/scripts/ice /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts; cd /scratch/genomic_med/apps/hic-pro/HiC-Pro-2.9.0/scripts/src/ice_mod/; /scratch/genomic_med/apps/python/anaconda/default/bin/python setup.py install --user;)
/scratch/genomic_med/apps/python/anaconda/default/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/scratch/genomic_med/apps/python/anaconda/default/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
Warning: Assuming default configuration (iced/utils/{setup_utils,setup}.py was not found)Appending iced.utils configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.utils')
Appending iced.datasets configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.datasets')
non-existing path in 'iced/io': '../src/cblas'
non-existing path in 'iced/io': '../src/cblas'
Appending iced.io configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.io')
non-existing path in 'iced': '../src/cblas'
non-existing path in 'iced': '../src/cblas'
Appending iced configuration to 
Ignoring attempt to set 'name' (from '' to 'iced')
running install
error: [Errno 13] Permission denied: '/scratch/genomic_med/mtang1/.local/lib/python2.7'
make: *** [iced] Error 1

```

UPDATE, I somehow disabled permission of my own .local/bin/python2.7 folder.
after `chmod 755 ~/.local/lib` it installed fine.

what if i want to use other places to install the python packages?
e.g. /scratch/genomic_med/apps/python/anaconda/default/lib

please see my config file:

```
cat config-system.txt 
#######################################################################
## HiC-Pro - System settings
#######################################################################
#######################################################################
## Required Software - Specified the DIRECTORY name of the executables
## If not specified, the program will try to locate the executable
## using the 'which' command
#######################################################################
R_PATH = /scratch/genomic_med/apps/R/R4py2/bin
BOWTIE2_PATH = /risapps/rhel5/bowtie2/2.2.3
SAMTOOLS_PATH = /scratch/genomic_med/apps/python/anaconda/default/bin
PYTHON_PATH = /scratch/genomic_med/apps/python/anaconda/default/bin
INSTALL_PATH = /scratch/genomic_med/apps/hic-pro/HiC-Pro_2.9.0
SCRIPTS = /scratch/genomic_med/apps/hic-pro/HiC-Pro_2.9.0/scripts
SOURCES = /scratch/genomic_med/apps/hic-pro/HiC-Pro_2.9.0/scripts/src
ANNOT_DIR = /scratch/genomic_med/apps/hic-pro/HiC-Pro_2.9.0/annotation
CLUSTER_SCRIPT = /scratch/genomic_med/apps/hic-pro/HiC-Pro_2.9.0/scripts/make_lsf_script.sh
```

**Comment by nservant** [comment]
Hi
The iced package is install with a pyton setup.py --user
If you want to install somewhere, you can still edit the Makefile, and change that ?
Best

**Comment by nservant** [comment]
Btw, as the config-system.txt looks complete, I think that if you manually install iced in the good python 
PYTHON_PATH = /scratch/genomic_med/apps/python/anaconda/default/bin
it will work ...

**Comment by crazyhottommy** [comment]
thanks for the reply.

I manually installed iced.
```
python setup.py install --prefix=/scratch/genomic_med/apps/python/anaconda/default/lib
/scratch/genomic_med/apps/python/anaconda/default/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/scratch/genomic_med/apps/python/anaconda/default/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
Warning: Assuming default configuration (iced/utils/{setup_utils,setup}.py was not found)Appending iced.utils configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.utils')
Appending iced.datasets configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.datasets')
non-existing path in 'iced/io': '../src/cblas'
non-existing path in 'iced/io': '../src/cblas'
Appending iced.io configuration to iced
Ignoring attempt to set 'name' (from 'iced' to 'iced.io')
non-existing path in 'iced': '../src/cblas'
non-existing path in 'iced': '../src/cblas'
Appending iced configuration to 
Ignoring attempt to set 'name' (from '' to 'iced')
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "iced.io.fastio_" sources
building extension "iced.io.read" sources
building extension "iced._normalization_" sources
building extension "iced._filter_" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
running build_scripts
running install_lib
running install_scripts
changing mode of /scratch/genomic_med/apps/python/anaconda/default/lib/bin/ice to 755
running install_data
running install_egg_info
Removing /scratch/genomic_med/apps/python/anaconda/default/lib/lib/python2.7/site-packages/iced-0.4.2-py2.7.egg-info
Writing /scratch/genomic_med/apps/python/anaconda/default/lib/lib/python2.7/site-packages/iced-0.4.2-py2.7.egg-info
running install_clib
customize UnixCCompiler
```
but got this error.

```
>>> import iced
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "iced/__init__.py", line 1, in <module>
    from . import normalization
  File "iced/normalization.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
ImportError: No module named _normalization_
```

**Comment by crazyhottommy** [comment]
No, worries, I fixed it.
thanks!
```
python setup.py install --prefix=/scratch/genomic_med/apps/python/anaconda/default/
```

**Comment by nservant** [comment]
ok great. I close.
N
