### ISSUE TITLE
HiC-Pro crashes in case of annotation unconformity

### ISSUE THREAD

**Issue by nservant** [nservant/HiC-Pro#13]
The Bowtie2 indexes for mm9 seem to use 'chrMT' instead of 'chrM' as provided in the annotation file. If so, HiC-Pro crashes during reads filtering :

--------------------------------------------
jeudi 12 mars 2015, 16:10:57 (UTC+0100)
Assign alignments to HindIII sites ...
/bioinfo/users/nservant/Apps/HiC-Pro_v2.4.0/scripts/mapped_2hic_fragments.sh -c /data/tmp/HiC_babraham/config-hicpro.txt >> TetMyc
Traceback (most recent call last):
  File "/bioinfo/users/nservant/Apps/HiC-Pro_v2.4.0/scripts/mapped_2hic_fragments.py", line 405, in <module>
    r1_resfrag = getOverlappingRestrictionFragment(resFrag, r1_chrom, r1)
  File "/bioinfo/users/nservant/Apps/HiC-Pro_v2.4.0/scripts/mapped_2hic_fragments.py", line 142, in getOverlappingRestrictionFragment
    resfrag = resFrag[chrom].find(pos, pos+1)
KeyError: 'chrMT'
make: *** [mapped_2hic_fragments] Erreur 1

**Comment by nservant** [comment]
Fixed. A warning is now print in the log file, and the reads pair is put in DUMP pairs
