### ISSUE TITLE
ice_error

### ISSUE THREAD

**Issue by hzaumsq** [nservant/HiC-Pro#204]
Using iced version 0.4.2
Loading files...
Traceback (most recent call last):
  File "/home/sqmao/tools/hicpro/HiC-Pro_2.11.1/scripts/ice", line 76, in <module>
    if min(i.min(), j.min()) == 0:
  File "/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by suipinpin** [comment]
Hi, I also met the same error. Have you succeed?
