### ISSUE TITLE
Error: can't find python dependencies

### ISSUE THREAD

**Issue by docdot** [nservant/HiC-Pro#221]
To whom it may concern,

I have followed the installation instructions, installing all dependencies. However, I'm receiving the following error:

```
(base)~/Software/HiC-Pro-master$ sudo make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory '/home/test/Software/HiC-Pro-master'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /usr/local/bin/HiC-Pro_2.11.1 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
./scripts/install/install_dependencies.sh: line 43: ((: 10#15rc1: value too great for base (error token is "10#15rc1")
./scripts/install/install_dependencies.sh: line 47: ((: 10#15rc1: value too great for base (error token is "10#15rc1")
Checking dependencies ... 
Checking Python libraries ...
Traceback (most recent call last):
  File "../scripts/install/check_pythonlib.py", line 28, in <module>
    raise ImportError('Error - bx-python cannot be imported')  
ImportError: Error - bx-python cannot be imported
Can not proceed without the required Python libraries, please install them and re-run
scripts/install/Makefile:37: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/home/test/Software/HiC-Pro-master'
Makefile:37: recipe for target 'configure' failed
make: *** [configure] Error 2
(base) test@test-Standard-PC-i440FX-PIIX-1996:~/Software/HiC-Pro-master$ source ~/.bashrc
test@test-Standard-PC-i440FX-PIIX-1996:~/Software/HiC-Pro-master$ sudo make configure
make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory '/home/test/Software/HiC-Pro-master'
./scripts/install/install_dependencies.sh -c ./config-install.txt -o  /usr/local/bin/HiC-Pro_2.11.1 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation ...
./scripts/install/install_dependencies.sh: line 43: ((: 10#15rc1: value too great for base (error token is "10#15rc1")
./scripts/install/install_dependencies.sh: line 47: ((: 10#15rc1: value too great for base (error token is "10#15rc1")
Checking dependencies ... 
Checking Python libraries ...
Traceback (most recent call last):
  File "../scripts/install/check_pythonlib.py", line 28, in <module>
    raise ImportError('Error - bx-python cannot be imported')  
ImportError: Error - bx-python cannot be imported
Can not proceed without the required Python libraries, please install them and re-run
scripts/install/Makefile:37: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
make[1]: Leaving directory '/home/test/Software/HiC-Pro-master'
Makefile:37: recipe for target 'configure' failed
make: *** [configure] Error 2
```

And all dependencies are installed (I also double checked the instalation of pysam (>=0.8.3), bx-python(>=0.5.0), numpy(>=1.8.2), and scipy(>=0.15.1) libraries by conda):

```
~/Software/HiC-Pro-master$ which python
/home/test/anaconda2/bin/python
~/Software/HiC-Pro-master$ which bowtie2
/usr/bin/bowtie2
~/Software/HiC-Pro-master$ which samtools
/home/test/anaconda2/bin/samtools
~/Software/HiC-Pro-master$ which R
/usr/bin/R
```

This was my config-install.txt 

```
#########################################################################
## Paths and Settings  - Start editing here !
#########################################################################

PREFIX = /usr/bin
BOWTIE2_PATH = /usr/bin/bowtie2
SAMTOOLS_PATH = /home/test/anaconda2/bin/samtools
R_PATH = /usr/bin/R
PYTHON_PATH = /home/test/anaconda2/bin/python
CLUSTER_SYS =

```

Any idea where is the issue causing this error?

**Comment by nservant** [comment]
Hi,
Are you sure that all dependencies are installed in /home/test/anaconda2/bin/python ?
If you simply run ;

/home/test/anaconda2/bin/python 
>> import bx.intervals

Does it work ?
N

**Comment by docdot** [comment]
Hi 
Thanks for the prompt reply. I did and I didn't receive any error message:

```
/home:~$ /home/test/anaconda2/bin/python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bx.intervals
>>> 

```

**Comment by docdot** [comment]
Hi,

I have found a workaround.
It seems that the problem is related to conda environment itself. I tried this solution here https://conda.io/docs/user-guide/troubleshooting.html#programs-fail-due-to-invoking-conda-python-instead-of-system-python but it didn't work.
So, I have uninstalled conda and all dependencies to install all again by PyPI.
It is working now.

Thanks,
Raphael

**Comment by nservant** [comment]
thanks. N
