### ISSUE TITLE
Trouble merging forward and reverse tags (".bam.bam"?)

### ISSUE THREAD

**Issue by vtartaglio** [nservant/HiC-Pro#242]
Hi,

Thanks for making HiC-Pro, I really like this program.

Hopefully my problem will be an easy fix. I am running HiC-Pro sequentially and I am having trouble with the proc_hic step. I am getting a funny error where one of the scripts is adding an extra ".bam" to my filename. 

I ran step 1, the mapping step, and I think it worked okay and the bam files were successfully sorted. Then I moved the *.bwt2merged.bam files from bowtie_results/bwt2/GHUTG/ to rawdata/GHUTG (my library is called GHUTG). In other words:
\> ls rawdata/GHUTG/
GHUTG.fastq  GHUTG_R1.fastq  GHUTG_R1_Bd21.bwt2merged.bam  GHUTG_R2.fastq  GHUTG_R2_Bd21.bwt2merged.bam

Now I try to run the proc_hic step. However, I am getting this error from results/logs/GHUTG/mergeSAM.log:
python mergeSAM.py -q 20 -t -v -f rawdata/GHUTG/GHUTG_R1_Bd21.bwt2merged.bam.bam -r rawdata/GHUTG/GHUTG_R2_Bd21.bwt2merged.bam.bam -o bowtie_results/bwt2/GHUTG/GHUTG_Bd21.bam.bwt2pairs.bam
[E::hts_open_format] Failed to open file rawdata/GHUTG/GHUTG_R1_Bd21.bwt2merged.bam.bam
\## mergeBAM.py
\## forward= rawdata/GHUTG/GHUTG_R1_Bd21.bwt2merged.bam.bam
\## reverse= rawdata/GHUTG/GHUTG_R2_Bd21.bwt2merged.bam.bam
\## output= bowtie_results/bwt2/GHUTG/GHUTG_Bd21.bam.bwt2pairs.bam
\## min mapq= 20
\## report_single= False
\## report_multi= False
\## verbose= True
\## Merging forward and reverse tags ...
Traceback (most recent call last):
  File "/global/projectb/sandbox/plant/hybridum/software/HiCPro/HiC-Pro_2.11.1/scripts/mergeSAM.py", line 222, in <module>
    with  pysam.Samfile(R1file, "rb") as hr1,  pysam.Samfile(R2file, "rb") as hr2: 
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 935, in pysam.libcalignmentfile.AlignmentFile._open
IOError: [Errno 2] could not open alignment file `rawdata/GHUTG/GHUTG_R1_Bd21.bwt2merged.bam.bam`: No such file or directory

Renaming the files to lack the '.bam' extension doesn't help, because then I just get an error saying that the bam files are missing. 

Sorry to bother you for such a little thing. I'm sure I'm making some silly mistake, but I really can't figure out what it is.

**Comment by vtartaglio** [comment]
Hi, 

I figured out the problem. I am working on a SLURM cluster and had failed to include an array specification in my batch script, e.g.:
#SBATCH --array=1-2
When I add this line to my batch script, the '.bam.bam' error disappears.
