### ISSUE TITLE
singularity HiC-Pro_2.11.3-beta/bin/../scripts//Makefile:191: recipe for target 'ice_norm' failed

### ISSUE THREAD

**Issue by amagli** [nservant/HiC-Pro#298]
Dear Nicholas,
First of all, happy 2020 :)

I have been attempting to run the latest singularity image but I am encountering a few issues:
1) analysis of the test dataset completes with no errors but the directories in hic_results/matrix/iced are empty. Is it just because the number of reads is just very small?

2) this is more critical. I have attempted to run the latest image (hicpro_devel_ubuntu.img) using my data and the analysis stops at the ICE normalization with this error:

Mon Dec 30 23:01:41 CST 2019
Run ICE Normalization ...
Logs: logs/plusdox_B/ice_10000.log
/usr/local/bin/HiC-Pro_2.11.3-beta/bin/../scripts//Makefile:191: recipe for target 'ice_norm' failed
make: *** [ice_norm] Error 1

I was looking at the previous reported issues (https://github.com/nservant/HiC-Pro/issues/231) and it seems there was a problem with the installation of iced in the root local python dir.
I tried to do this (see below):
$ singularity exec hicpro_devel_ubuntu.img python
$ import iced
and I got this result:

$ singularity exec hicpro_devel_ubuntu.img python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Jun 15 2016, 15:21:30)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
$ import iced
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/perlinge/amagli/.local/lib/python2.7/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/home/perlinge/amagli/.local/lib/python2.7/site-packages/iced/normalization.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
ImportError: /home/perlinge/amagli/.local/lib/python2.7/site-packages/iced/_normalization_.so: undefined symbol: PyUnicodeUCS2_Format

Do you have an idea of what could be the problem?
Thank you very much,
Alessandro

**Comment by nservant** [comment]
Hi Alessandro
Thanks for reporting this issue. I will try to generate a new image and come back to you
best

**Comment by nservant** [comment]
Hi Alessandro,

I just build a new Singularity image at http://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_2.11.3_ubuntu.img
Hope it helps
Nicolas

```
(base) nservant@nservant-bioinfo-laptop:~/GIT/HiC-Pro$ singularity exec hicpro_2.11.3_ubuntu.img python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iced
>>> 
```

**Comment by amagli** [comment]
Thank you very much Nicolas.

Best,
Alessandro
