### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size

### ISSUE THREAD

**Issue by lanliting** [nservant/HiC-Pro#330]
Hi，
I got the following problem in iced normalization step, can you help me?

cat ice_40000.log
ice --results_filename hic_results/matrix/NSD2-High-SRR9109486/iced/40000/NSD2-High-SRR9109486_40000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//NSD2-High-SRR9109486/raw/40000/NSD2-High-SRR9109486_40000.matrix
Traceback (most recent call last):
  File "/usr/bin/ice", line 8, in <module>
    import iced
  File "/home/limoon/.local/lib/python2.7/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/home/limoon/.local/lib/python2.7/site-packages/iced/normalization.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
  File "__init__.pxd", line 861, in init iced._normalization_ (iced/_normalization_.c:4673)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by nservant** [comment]
Hi,
As explained in the error message, I think that numpy is not correclty installed.
Could you try to install it again
Thanks
