### ISSUE TITLE
Error during ICE normalization

### ISSUE THREAD

**Issue by mxw010** [nservant/HiC-Pro#348]
Hi,

I encountered an error during normalization and I wonder if you guy can help me with it. Here is the output from SLURM:

```
 Wed Jul 22 07:49:50 EDT 2020
 Run ICE Normalization ...
 Logs: logs/SEG0084/ice_20000.log
 make: *** [/opt/HiC-Pro/scripts/Makefile:194: ice_norm] Error 1
```
Everything to this point ran without error. So I cat logs:

```
ice --results_filename hic_results/matrix/SEG0084/iced/20000/SEG0084_20000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 hic_results/matrix//SEG0084/raw/20000/SEG0084_20000.matrix
/opt/python/3.7.3/envs/HiC-Pro_v3.0.0/lib/python3.7/site-packages/iced/normalization/_ca_utils.py:9: UserWarning: The API of this module is likely to change. Use only for testing purposes
  "The API of this module is likely to change. "
Traceback (most recent call last):
  File "/opt/HiC-Pro/scripts/ice", line 73, in <module>
    i, j, data = loadtxt(filename).T
  File "/home/gdlessnicklab/mxw010/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1100, in loadtxt
    first_vals = split_line(first_line)
  File "/home/gdlessnicklab/mxw010/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1040, in split_line
    line = regex_comments.split(line, maxsplit=1)[0]
TypeError: expected string or bytes-like object
````

Version of HiC-Pro is 3.0.0.

```
> head hic_results/matrix//SEG0084/raw/20000/SEG0084_20000.matrix
1	50693	1
3	17623	1
3	68120	1
3	119408	1
3	121604	1
4	132896	1

> wc -l hic_results/matrix//SEG0084/raw/20000/SEG0084_20000.matrix
10237981 hic_results/matrix//SEG0084/raw/20000/SEG0084_20000.matrix
```

Much appreciated.

**Comment by nservant** [comment]
Hi,
Which iced version are you using please ?
I think you should update it to the latest version
Best
