### ISSUE TITLE
sparseToDense.py error 

### ISSUE THREAD

**Issue by sunthink** [nservant/HiC-Pro#387]
Hi, when I use sparseToDense.py:    ./sparseToDense.py -h

 I get this error：

Traceback (most recent call last):
  File "./sparseToDense.py", line 6, in <module>
    from iced import io
  File "/public/home/cmsun/.local/lib/python2.7/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/public/home/cmsun/.local/lib/python2.7/site-packages/iced/normalization.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
  File "__init__.pxd", line 861, in init iced._normalization_ (iced/_normalization_.c:4673)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

But other scripts work well and don't report any error. I use numpy=1.10.4, hic-pro=2.11.4. Do you have any advice?

Thank you,
Chengming

**Comment by nservant** [comment]
Hi,
I'm not an expert, but it looks like you have an installation issue with numpy.
Could you try to reinstall it ?
Best

**Comment by sunthink** [comment]
Hi,

When I try to uninstall and reinstall numpy with conda, I still get the same error. But when I use pip to install, it works.

Thank you
