### ISSUE TITLE
Error with Ice

### ISSUE THREAD

**Issue by PFRoux** [nservant/HiC-Pro#422]
Hello !

First of all, I would like to thank you for this great tool.

I am nevertheless getting the following error at the step of the ICE normalization : 

```
Run ICE Normalization ...
Logs: logs/dixon_2M/ice_500000.log
make: *** [ice_norm] Erreur 1
```

When checking at the .log file :

```
/tools/python/2.7.2/bin/python /usr/local/bioinfo/src/HiC-Pro/HiC-Pro_2.11.1/scripts/ice --results_filename hic_results/matrix/dixon_2M/ic
ed/500000/dixon_2M_500000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zero
s-loci --output-bias 1 --verbose 1 hic_results/matrix//dixon_2M/raw/500000/dixon_2M_500000.matrix
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/HiC-Pro/HiC-Pro_2.11.1/scripts/ice", line 5, in <module>
    import numpy as np
  File "/home/pfroux/.local/lib/python3.7/site-packages/numpy/__init__.py", line 131
    raise ImportError(msg) from e
                              ^
SyntaxError: invalid syntax
```

I then tried to directly run the commande line : 

```
pfroux@genologin1 ~/work/TEST_HICPRO $ python /usr/local/bioinfo/src/HiC-Pro/HiC-Pro_2.11.1/scripts/ice --results_filename hic_results/matrix/dixon_2M/iced/500000/dixon_2M_500000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 --verbose 1 hic_results/matrix//dixon_2M/raw/500000/dixon_2M_500000.matrix
  File "/usr/local/bioinfo/src/HiC-Pro/HiC-Pro_2.11.1/scripts/ice", line 58
    print "--filtering_perc is deprecated. Please use filter_low_counts_perc"
                                                                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("--filtering_perc is deprecated. Please use filter_low_counts_perc")?
```

I am running iced 0.5.8 with Python 3.7.4.

Thanks a lot for your help.

Pef

**Comment by PFRoux** [comment]
I figured this out. Thanks !
