### ISSUE TITLE
ICE normalization failure due to conflict between iced/io and standard io package

### ISSUE THREAD

**Issue by kmnam** [nservant/HiC-Pro#43]
It appears that, in my installation of HiC-Pro / iced, problems arise when I attempt to run ICE normalization because of a naming conflict between the standard io Python package (used by tempfile) and the io package that comes with iced. This leads to errors that can be rectified by changing the order of imports, which is a sign of something strange going on in the code.

For instance, after installing HiC-Pro, I can't import iced directly:

(venv)kmn7@loge:~/park/hicpro/HiC-Pro_2.7.7$ python
Python 2.7.6 (default, Aug  3 2015, 17:43:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iced
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kmn7/venv/lib/python2.7/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/home/kmn7/venv/lib/python2.7/site-packages/iced/normalization.py", line 1, in <module>
    import numpy as np
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/core/__init__.py", line 57, in <module>
    from numpy.testing import Tester
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp
  File "/opt/python-2.7.6/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/kmn7/venv/lib/python2.7/site-packages/io/__init__.py", line 1, in <module>
    from .fastio_ import loadtxt, savetxt
  File "__init__.pxd", line 155, in init iced.io.fastio_ (iced/io/fastio_.c:4789)
AttributeError: 'module' object has no attribute 'dtype'
>>> 

Or even tempfile:

(venv)kmn7@loge:~/park/hicpro/HiC-Pro_2.7.7$ python
imPython 2.7.6 (default, Aug  3 2015, 17:43:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-2.7.6/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/kmn7/venv/lib/python2.7/site-packages/io/__init__.py", line 1, in <module>
    from .fastio_ import loadtxt, savetxt
  File "__init__.pxd", line 155, in init iced.io.fastio_ (iced/io/fastio_.c:4789)
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/core/__init__.py", line 57, in <module>
    from numpy.testing import Tester
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/opt/python-2.7.6/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp
ImportError: cannot import name mkdtemp
>>> 

This is presumably because tempfile requires the standard io package (https://docs.python.org/2/library/io.html); we can confirm this by running:

(venv)kmn7@loge:~/park/hicpro/HiC-Pro_2.7.7$ python 
Python 2.7.6 (default, Aug  3 2015, 17:43:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0,'/opt/python-2.7.6/lib/python2.7')
>>> import tempfile
>>> 

But if I import io first, then I can import iced and tempfile without any problems:

(venv)kmn7@loge:~/park/hicpro/HiC-Pro_2.7.7$ python
Python 2.7.6 (default, Aug  3 2015, 17:43:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> io.__file__
'/home/kmn7/venv/lib/python2.7/site-packages/io/__init__.pyc'
>>> import tempfile
>>> import iced
>>> 

Might renaming the io package be a quick fix for this anomaly?

Thank you for your help!

Best,
Chris Nam

**Comment by kmnam** [comment]
It appears that I may have resolved the issue: changing PYTHONPATH so that it points to the standard io package first seems to do the trick. All tests seem to run smoothly.

**Comment by nservant** [comment]
Thank you Chris. It's good to know.
Nicolas
