### ISSUE TITLE
hicpro2juicer.sh issue: no output

### ISSUE THREAD

**Issue by Paladin258** [nservant/HiC-Pro#443]
Hello,

I'm running hicpro2juicer.sh to make hic file for visualization with I don't get any output files. Here is my command:

/HiC-Pro-3.0.0/3.0.0/bin/utils/hicpro2juicebox.sh -i HiC_1.allValidPairs \
-j /juice_box/Juicebox-master/out/artifacts/juicer_tools_jar/juicer_tools.jar \
-r RE_file -g hg38_size -o out_files

the log below seems to indicate the job finished but I don't see any output. Any help will be appreciated. 

HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
Running Juicebox ...
WARN [2021-05-25T23:17:48,249]  [Globals.java:138] [main]  Development mode is enabled
Using 1 CPU thread(s)
Start preprocess
Writing header
Writing body
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/math3/stat/descriptive/DescriptiveStatistics
	at juicebox.tools.utils.original.MatrixZoomDataPP.computeStats(MatrixZoomDataPP.java:675)
	at juicebox.tools.utils.original.MatrixZoomDataPP.mergeAndWriteBlocks(MatrixZoomDataPP.java:482)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:1038)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:675)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:434)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:161)
	at juicebox.tools.HiCTools.main(HiCTools.java:94)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.stat.descriptive.DescriptiveStatistics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
done !

**Comment by nservant** [comment]
Hi,
Which Juicer version are you using please ?
Would you have any files in the temporary folder ?
Thanks

**Comment by Paladin258** [comment]
Hello, 

Thank you for your response. I'm currently using their most recent juicer version 1.5. There were some files in the tpm folder when I monitored the job but no files saved anywhere when it's done.

**Comment by Paladin258** [comment]
Hi,

Sorry for your time. I was able to resolve the issues.
