### ISSUE TITLE
hicpro2juicebox.sh

### ISSUE THREAD

**Issue by Paladin258** [nservant/HiC-Pro#446]
Hello,

I used to use hicpro2juicebox.sh to convert hicpro valid pairs to hic for Juicebox with 2 steps:
step 1: use hicpro2juicebox.sh with Juicebox.jar to make pre hic files
step 2: juicer_tools.jar with pre command on pre_sorted from step 1 to make hic

Years later, I installed new version Hicpro 3.0 and new juicer tools. From all the threads I've read, it seems hicpro2juicebox.sh now uses juicer_tools.jar instead of Juicebox.jar with 1 step to make hic files. Correct me if I'm wrong on that. I'm still a little confused. So I tried and it does not seem to work. My hic file appears small (66M instead of 1-2 GB) and it does not work on Juicebox software. Please any help will be appreciated.

**Comment by nservant** [comment]
Hi
Yes, it uses the Juicer command line, and not Juicebox.
Do you have any messages, something, to validate that there is an issue with your file ?
N

**Comment by Paladin258** [comment]
Hi,

Here is the log:

HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
Running Juicebox ...
WARN [2021-05-26T14:02:03,096]  [Globals.java:138] [main]  Development mode is enabled
Using 1 CPU thread(s)
Not including fragment map
Start preprocess
Writing header
Writing body
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/math3/stat/descriptive/DescriptiveStatistics
	at juicebox.tools.utils.original.MatrixZoomDataPP.computeStats(MatrixZoomDataPP.java:675)
	at juicebox.tools.utils.original.MatrixZoomDataPP.mergeAndWriteBlocks(MatrixZoomDataPP.java:482)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:1038)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:675)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:434)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:161)
	at juicebox.tools.HiCTools.main(HiCTools.java:94)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.stat.descriptive.DescriptiveStatistics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
done !

I'm not sure if it could relate to memory issues. It says using 1 CPU thread(s).

**Comment by raquelsofi** [comment]
Hi i'm having similar issue, could you identify which jar file works to run the hicpro2juicebox.sh utility? On my situation it creates the Temp folder and then crashes with issue with the jar file.

Thank you,
Raquel
