### ISSUE TITLE
hicpro2juicebox.sh NullPointerException at zoom FRAG_20

### ISSUE THREAD

**Issue by esebesty** [nservant/HiC-Pro#463]
I'm trying to convert the result files with `hicpro2juicebox.sh` but getting the following error.

<details>
  <summary>Error message</summary>

```
HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
Running Juicebox ...
WARN [2021-07-27T19:02:37,145]  [Globals.java:138] [main]  Development mode is enabled
Using 1 CPU thread(s)
Start preprocess
Writing header
Writing body
......................................................................................................................................................................................................................................................................................................................................
Writing footer
nBytesV5: 1893810
masterIndexPosition: 706792378

Finished preprocess

Calculating norms for zoom BP_2500000
Calculating norms for zoom BP_1000000
Calculating norms for zoom BP_500000
Calculating norms for zoom BP_250000
Calculating norms for zoom BP_100000
Calculating norms for zoom BP_50000
Calculating norms for zoom BP_25000
Calculating norms for zoom BP_10000
Calculating norms for zoom BP_5000
Calculating norms for zoom BP_1000
Calculating norms for zoom FRAG_500
Calculating norms for zoom FRAG_200
Calculating norms for zoom FRAG_100
Calculating norms for zoom FRAG_50
Calculating norms for zoom FRAG_20java.lang.NullPointerException
        at juicebox.data.iterator.ListOfListIterator.hasNext(ListOfListIterator.java:45)
        at juicebox.data.iterator.IteratorContainer.getNumberOfContactRecords(IteratorContainer.java:51)
        at juicebox.data.iterator.ListOfListIteratorContainer.getIsThereEnoughMemoryForNormCalculation(ListOfListIteratorContainer.java:52)
        at juicebox.tools.utils.norm.NormalizationCalculations.<init>(NormalizationCalculations.java:59)
        at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:178)
        at juicebox.tools.clt.old.AddNorm.launch(AddNorm.java:87)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:170)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)
done !
```
</details>

Not sure if this is a memory issue, the node I'm using has ~32Gb memory. Have you seen this error?

Update: probably not memory related, as sampling 1M or 500k reads does not help, and the error happens trying to process different files/samples.

**Comment by esebesty** [comment]
Conversion works without the restriction fragment site file.
