### ISSUE TITLE
Can not proceed without the required Python libraries, please install them and re-run

### ISSUE THREAD

**Issue by Giuseppe1995** [nservant/HiC-Pro#484]
Hi!
I am trying to install HiC-Pro 3.1.0 following the instructions on its github page [github page](https://github.com/nservant/HiC-Pro). When I try to configure HiC-Pro by typing ` make configure` in HiC-Pro-master directory, but the terminal returns me the following error: 

make -f ./scripts/install/Makefile CONFIG_SYS=./config-install.txt
make[1]: Entering directory '/srv/ngs/analysis/dalteriog/Tools/HiC-Pro-master'
./scripts/install/install_dependencies.sh -c ./config-install.txt -p /usr/local/bin/ -o /usr/local/bin//HiC-Pro_3.1.0 -q
Make sure internet connection works for your shell prompt under current user's privilege ...
Starting HiC-Pro installation !
Checking dependencies
- Python libraries ...
Can not proceed without the required Python libraries, please install them and re-run
make[1]: *** [scripts/install/Makefile:41: configure] Error 1
make[1]: Leaving directory '/srv/ngs/analysis/dalteriog/Tools/HiC-Pro-master'
make: *** [Makefile:40: configure] Error 2

Obviously, I installed all the requested Python library trough `pip install`:

`pip list`

Package    Version

bx-python  0.8.11
numpy      1.21.2
pip        21.2.4
pysam      0.17.0
scipy      1.7.1
setuptools 58.0.4
wheel      0.37.0

I can't figure out what I am missing! 
Giuseppe

**Comment by Adeel3Dgenomics** [comment]
Hi Giuseppe, 
Please see the "tmp" folder in ~/HiC-Pro-master , you will find the specific library's error. 
In my case i was facing 'bx' version conflict and solved using  pip install bx-python==0.8.8 
try this hope it will help.
best, 
adeel

**Comment by Giuseppe1995** [comment]
Thank you so much! I have solved this problem as follows:
I ran the command  `cat ${INSTALLATION_DIR}/HiC-Pro-master/check_python.log`
that gave me the following output: 

Traceback (most recent call last):
  File "/srv/ngs/analysis/dalteriog/Tools/HiC-Pro-master/tmp/../scripts/install/check_pythonlib.py", line 69, in <module>
    import iced
ModuleNotFoundError: No module named 'iced'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/ngs/analysis/dalteriog/Tools/HiC-Pro-master/tmp/../scripts/install/check_pythonlib.py", line 73, in <module>
    raise ImportError('Error - iced cannot be imported')
ImportError: Error - iced cannot be imported. 
So, all I did was to install 'iced' package of Python, and slved the problem.
I would therefore suggest to add this package among the dependencies of HiC-Pro-master.

Thank you again,
Giuseppe

**Comment by chiawenwang** [comment]
> Thank you so much! I have solved this problem as follows: I ran the command `cat ${INSTALLATION_DIR}/HiC-Pro-master/check_python.log` that gave me the following output:
> 
> Traceback (most recent call last): File "/srv/ngs/analysis/dalteriog/Tools/HiC-Pro-master/tmp/../scripts/install/check_pythonlib.py", line 69, in import iced ModuleNotFoundError: No module named 'iced'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/srv/ngs/analysis/dalteriog/Tools/HiC-Pro-master/tmp/../scripts/install/check_pythonlib.py", line 73, in raise ImportError('Error - iced cannot be imported') ImportError: Error - iced cannot be imported. So, all I did was to install 'iced' package of Python, and slved the problem. I would therefore suggest to add this package among the dependencies of HiC-Pro-master.
> 
> Thank you again, Giuseppe

hello，I meet the same problem,but I can't find the `${INSTALLATION_DIR}/HiC-Pro-master/check_python.log`,there is also no `tmp` in the HiC-Pro.can u show me your directory file?

**Comment by marshals1999** [comment]
you'd better download the latest version of Hic-pro software, and tar -zxvf HiC-Pro-3.1.0.tar.gz, and then you will find the  config-install.txt file in the stall directory, you need to modify it according to the dependent file install path in your server. such as this:

PREFIX =         ### this can be blank or fill your the installation folder path.
BOWTIE2_PATH = /anaconda3/bin/bowtie2 
SAMTOOLS_PATH = /software/samtools-1.10/samtools
R_PATH = /usr/bin/R
PYTHON_PATH = /anaconda3/bin/python
CLUSTER_SYS = TORQUE

in addition, you need install dependent python modules by "pip install modules name" according to the introduction of HiC-pro software in Github. and finally you can run the command "make configure" and "make install or sudo make install" in the install directory. It will be OK!
