### ISSUE TITLE
hicpro2juicer.sh out of memory 87980 Segmentation fault

### ISSUE THREAD

**Issue by wulisling** [nservant/HiC-Pro#501]
hi, 
I was hoping to get some help as while I used hicpro2juicer.sh, I got the error:

`/lustre/home/acct-medhdl/medhdl/software/HiC-Pro_3.0.0/bin/utils/hicpro2juicebox.sh: line 142: 87979 Done                    awk '{$4=$4!="+"; $7=$7!="+"} $2<=$5{print $1, $4, $2, $3, 0, $7, $5, $6, 1, $11, $12 }$5<$2{ print $1, $7, $5, $6, 0, $4, $2, $3, 1, $12, $11 }' $VALIDPAIRS
     87980 Segmentation fault      | sort -T ${TEMP} -k3,3d -k7,7d -S 50% --parallel=4 > ${TEMP}/$$_allValidPairs.pre_juicebox_sorted
Not enough memory, skipping 1
Not enough memory, skipping 2
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at juicebox.data.DatasetReaderV2.readBlock(DatasetReaderV2.java:788)
        at juicebox.data.DatasetReaderV2.readNormalizedBlock(DatasetReaderV2.java:680)
        at juicebox.data.ContactRecordIterator.hasNext(ContactRecordIterator.java:81)
        at juicebox.data.MatrixZoomData.getContactRecordList(MatrixZoomData.java:1139)
        at juicebox.data.MatrixZoomData.getNumberOfContactRecords(MatrixZoomData.java:1164)
        at juicebox.tools.utils.norm.NormalizationCalculations.<init>(NormalizationCalculations.java:67)
        at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:132)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:151)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)`

my code was as followed:
`$hic2juice -i ${validir}one.allValidPairs -g $genomesize -j ${juicertool} -o /lustre/home/acct-medhdl/medhdl/data/hic/juicerfile/hicfile/onefile/`

The memory of the running node is 32G/CPU, and increasing the memory does not solve the problem. Whether I use 8 cpus or 12 cpus, the result is always the same because the script seems to be running on only one CPU. Is there any way to solve this problem?

Thanks in advance,
Edith

**Comment by nservant** [comment]
Hi Edith,
I guess the error comes from the `sort` command, but I'm surprised that it runs on only 1 CPU as in the error message you have `sort -T ${TEMP} -k3,3d -k7,7d -S 50% --parallel=4`
Maybe you can first check that the option we used in sort are available on your system ?
Then, you can try to modify them to have the command running without any memory issue ...
Best

**Comment by wulisling** [comment]
Thank you very much,
I modified the `SORT` command to fix this, but still ran out of memory when running the Juicer pre command. Finally I changed the parameters of the `Java -Xmx400g` and `Pre -j 20` command and it worked!
Edith
