### ISSUE TITLE
Cannot run ICE normalization on the test dataset with Singularity image

### ISSUE THREAD

**Issue by pierrepo** [nservant/HiC-Pro#524]
Hello,

I'm trying to run HiC-Pro with the Singularity image on the test [dataset](https://github.com/nservant/HiC-Pro#test-dataset).

Here are the steps I followed:

```bash
# Create target directory
$ mkdir -p /home/pierre/scratch/test_HiC-Pro
$ cd /home/pierre/scratch/test_HiC-Pro
# Download test dataset
$ wget --ciphers=DEFAULT:@SECLEVEL=1 https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz
$ tar -zxvf HiCPro_testdata.tar.gz
$ cp config_test_latest.txt config_test_latest_ori.txt
# Download Singularity image
wget --ciphers=DEFAULT:@SECLEVEL=1 https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_3.1.0_ubuntu.img
```

Then I downloaded the human genome sequence and chromosome size:

```bash
$ wget https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/latest/hg19.fa.gz
$ gunzip hg19.fa.gz
$ wget https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/latest/hg19.chrom.sizes
```

Built genome indexes:

```bash
$ mkdir -b bowtie2_indexes
$ singularity exec hicpro_3.1.0_ubuntu.img bowtie2-build --threads 4 hg19.fa bowtie2_indexes/hg19
```
Updated HiC-Pro config file. These are the differences with the template provided with the test dataset:

```bash
$ diff config_test_latest_ori.txt config_test_latest.txt 
39c39
< BOWTIE2_IDX_PATH = /data/annotations/Human/hg19/bowtie2_indexes/base/
---
> BOWTIE2_IDX_PATH = /home/pierre/scratch/test_HiC-Pro/bowtie2_indexes/
48c48
< GENOME_SIZE = chrom_hg19.sizes
---
> GENOME_SIZE = /home/pierre/scratch/test_HiC-Pro/hg19.chrom.sizes
```

And eventually ran HiC-Pro:

```bash
$ singularity exec hicpro_3.1.0_ubuntu.img HiC-Pro -c config_test_latest.txt -i test_data/ -o hicpro_latest_test
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-binutils_linux-64.sh:8:18: parameter expansion requires a literal
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-gcc_linux-64.sh:8:18: parameter expansion requires a literal
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-gfortran_linux-64.sh:8:18: parameter expansion requires a literal
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-gxx_linux-64.sh:8:18: parameter expansion requires a literal
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Warning: /home/pierre/scratch/test_HiC-Pro/HindIII_resfrag_hg19.bed not found. Look into the annotation folder ...

Run HiC-Pro 3.1.0
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:12:25 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Bowtie2 alignment step1 ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/mapping_step1.log
Logs: logs/dixon_2M_2/mapping_step1.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:13:11 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Bowtie2 alignment step2 ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/mapping_step2.log
Logs: logs/dixon_2M_2/mapping_step2.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:13:23 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Combine R1/R2 alignment files ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/mapping_combine.log
Logs: logs/dixon_2M_2/mapping_combine.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:13:25 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Mapping statistics for R1 and R2 tags ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/mapping_stats.log
Logs: logs/dixon_2M_2/mapping_stats.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:13:25 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Pairing of R1 and R2 tags ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/mergeSAM.log
Logs: logs/dixon_2M_2/mergeSAM.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:13:30 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Assign alignments to restriction fragments ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/mapped_2hic_fragments.log
Logs: logs/dixon_2M_2/mapped_2hic_fragments.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:14:01 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Merge chunks from the same sample ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/merge_valid_interactions.log
Logs: logs/dixon_2M_2/merge_valid_interactions.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:14:01 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Merge stat files per sample ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/merge_stats.log
Logs: logs/dixon_2M_2/merge_stats.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:14:01 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Run quality checks for all samples ...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/make_Rplots.log
Logs: logs/dixon_2M_2/make_Rplots.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:14:09 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Generate binned matrix files ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/build_raw_maps.log
Logs: logs/dixon_2M_2/build_raw_maps.log

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Mon Apr 25 09:14:10 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Run ICE Normalization ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/ice_500000.log
make: *** [/usr/local/bin/HiC-Pro_3.1.0/bin/../scripts//Makefile:194: ice_norm] Error 1
```

The output of `logs/dixon_2M/ice_500000.log` is:

```
/usr/local/conda/envs/hicpro/bin/python /usr/local/bin//HiC-Pro_3.1.0/scripts/ice --results_filename hic_results/matrix/dixon_2M/iced/500000/dixon_2M_500000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 hic_results/matrix//dixon_2M/raw/500000/dixon_2M_500000.matrix
/usr/local/bin//HiC-Pro_3.1.0/scripts/ice:65: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if "--filtering_perc" is None and "--filter_low_counts_perc" not in sys.argv:
Traceback (most recent call last):
  File "/usr/local/bin//HiC-Pro_3.1.0/scripts/ice", line 8, in <module>
    import iced
  File "/home/pierre/.local/lib/python3.8/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/home/pierre/.local/lib/python3.8/site-packages/iced/normalization/__init__.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
  File "__init__.pxd", line 242, in init iced.normalization._normalization_
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Do you know is this error comes from the Singularity image itself or a wrong parameter in the conf file `config_test_latest.txt`?

**Comment by nservant** [comment]
I think it may not used the right `iced` version. Do you have a local `iced` installation (which could be used instead of the one within the singularity image) ?
Otherwise, you could try to update the `iced` python package.

**Comment by pierrepo** [comment]
Hello @nservant well spotted :mag:  I indeed had a rogue `iced` installed on my machine.

I uninstalled it and managed to get HiC-Pro worked all the way through:

```bash
$ singularity exec hicpro_3.1.0_ubuntu.img HiC-Pro -c config_test_latest.txt -i test_data/ -o hicpro_latest_test
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-binutils_linux-64.sh:8:18: parameter expansion requires a literal
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-gcc_linux-64.sh:8:18: parameter expansion requires a literal
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-gfortran_linux-64.sh:8:18: parameter expansion requires a literal
source: /usr/local/conda/envs/hicpro/etc/conda/activate.d/activate-gxx_linux-64.sh:8:18: parameter expansion requires a literal
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Warning: /home/pierre/scratch/test_HiC-Pro/HindIII_resfrag_hg19.bed not found. Look into the annotation folder ...

Run HiC-Pro 3.1.0
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
--------------------------------------------
Tue Apr 26 12:42:34 CEST 2022
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Bowtie2 alignment step1 ...

[...]
Run ICE Normalization ...
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
Logs: logs/dixon_2M/ice_500000.log
Logs: logs/dixon_2M/ice_1000000.log
Logs: logs/dixon_2M_2/ice_500000.log
Logs: logs/dixon_2M_2/ice_1000000.log
```

Many thanks for your help :pray: 

You can close this issue.
