### ISSUE TITLE
HiC-Pro error in docker

### ISSUE THREAD

**Issue by voluptatis** [nservant/HiC-Pro#532]
I use the docker image to use Hic-pro, but an error occurred when align fastq to genome.
my code is 
`./HiC-Pro_3.0.0/bin/HiC-Pro -i /home/biosoft/juicer/work/test/ -o /home/trial/hic/ -c /home/biosoft/HiC-Pro/config.txt
root@85cf4bd0c191:/# ./HiC-Pro_3.0.0/bin/HiC-Pro -i /home/biosoft/juicer/work/test/ -o /home/trial/hic/ -c /home/biosoft/HiC-Pro/config.txt`
the error is `Pairing of R1 and R2 tags ...
Logs: logs/fastq/mergeSAM.log
make: *** [/HiC-Pro_3.0.0/bin/../scripts//Makefile:144: bowtie_pairing] Error 1`

**Comment by d0minicO** [comment]
same error for me running from singularity container.
error:
Pairing of R1 and R2 tags ...
Logs: logs/NSD2_High_1_Hi-C/mergeSAM.log
make: *** [/usr/local/bin/HiC-Pro_3.1.0/bin/../scripts//Makefile:144: bowtie_pairing] Error 1

mergeSAM.log:
/usr/local/conda/envs/hicpro/bin/python /usr/local/bin//HiC-Pro_3.1.0/scripts/mergeSAM.py -q 0 -t -v -f bowtie_results/bwt2/NSD2_High_1_Hi-C/NSD2_High_1_Hi-C_1_R1_rDNA.bwt2merged.bam -r bowtie_results/bwt2/NSD2_High_1_Hi-C/NSD2_High_1_Hi-C_1_R2_rDNA.bwt2merged.bam -o bowtie_results/bwt2/NSD2_High_1_Hi-C/NSD2_High_1_Hi-C_1_rDNA.bwt2pairs.bam
Traceback (most recent call last):
  File "/usr/local/bin//HiC-Pro_3.1.0/scripts/mergeSAM.py", line 21, in <module>
    import pysam
  File "/home/dowens/.local/lib/python3.8/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ImportError: /home/dowens/.local/lib/python3.8/site-packages/pysam/libcbcftools.cpython-38-x86_64-linux-gnu.so: undefined symbol: hts_idx_nseq

Looks like something is wrong with the python packages. I'm wondering if the singularity container still requires python + packages on the system and they are not included in the singularity container. Still, I installed them onto the system python and got the exact same error
