### ISSUE TITLE
Error with iced normalization

### ISSUE THREAD

**Issue by hillbluff** [nservant/HiC-Pro#541]
I am using HiC-Pro-3.0.0 and iced version 0.5.10. HiC-Pro runs fine until the iced normalization step. It outputs all of the raw matrices but none of the iced matrices. The error message from the ice_5000.log file is:

ice --results_filename hic_results/matrix/sample1/iced/5000/sample1_5000_iced.matrix --filter_low_counts_perc 0.02 --filter_high_counts_perc 0 --max_iter 100 --eps 0.1 --remove-all-zeros-loci --output-bias 1 hic_results/matrix//sample1/raw/5000/sample1_5000.matrix
/software/anaconda3/bin/ice:65: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if "--filtering_perc" is None and "--filter_low_counts_perc" not in sys.argv:
Traceback (most recent call last):
  File "/software/anaconda3/bin/ice", line 8, in <module>
    import iced
  File "/software/anaconda3/lib/python3.8/site-packages/iced/__init__.py", line 1, in <module>
    from . import normalization
  File "/software/anaconda3/lib/python3.8/site-packages/iced/normalization/__init__.py", line 3, in <module>
    from ._normalization_ import _update_normalization_csr
  File "__init__.pxd", line 242, in init iced.normalization._normalization_
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Can you assist me with this issue?

**Comment by hillbluff** [comment]
This issue was fixed by upgrading numpy from 1.20.3 to 1.23.0. HiC-Pro then generated all of the iced matrices along with the raw matrices.
