### ISSUE TITLE
Singularity image link

### ISSUE THREAD

**Issue by mangiruben** [nservant/HiC-Pro#565]
What is the updated link for the singularity image? the one provided in the README(https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_latest_ubuntu.img) does not work.

**Comment by d0minicO** [comment]
https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_3.1.0_ubuntu.img worked for me

**Comment by Matheo-LESNE** [comment]
Hey everyone,

I also encountered some troubles with the zerkalo link. For example, here is the output when I tried to download the test dataset:

``--2023-02-21 15:37:21--  https://zerkalo.curie.fr/partage/HiC-Pro/HiCPro_testdata.tar.gz``
``Resolving zerkalo.curie.fr (zerkalo.curie.fr)... failed: Name or service not known.``
``wget: unable to resolve host address ‘zerkalo.curie.fr’``


To download the singularity image, I found another way to get it with this command (https://singularityhub.github.io/singularityhub-archive/containers/DoaneAS-HiC-Pro-latest/), which will give the .sif directly:
``
singularity pull shub://DoaneAS/HiC-Pro:latest
``

And you can use the .sif to run it:
``singularity exec HiC-Pro_latest.sif HiC-Pro -h``

Hope this could help.

**Comment by pierrepo** [comment]
Hello,
The download link of the Singularity image is down:
```
https://zerkalo.curie.fr/partage/HiC-Pro/singularity_images/hicpro_latest_ubuntu.img
```
and the Singularity image available at https://singularityhub.github.io/singularityhub-archive/containers/DoaneAS-HiC-Pro-latest/ seems quite old since the build date is 2019 and HiC-Pro 3.1.0 has been released in 2021.

@nservant could you please reactivate the Zerkalo server?

**Comment by jeff-godwin** [comment]
I'm having the same issue. Following this thread for a solution.

Thanks in advance,
Jeff

**Comment by gayahaber** [comment]
While trying to generate trainable/predictable data in in GM12878 cell line :
python data_generate.py -hr 10kb -lr 40kb -s train -chunk 40 -stride 40 -bound 201 -scale 1 -c GM12878 -lrc 100

I have an error :
Going to read 10kb and 40kb data, then deviding matrices with nonpool
Making directory: /DeepHiC/raw/data
Traceback (most recent call last):
File "/home/DeepHiC-master/data_generate.py", line 58, in
mkdir(out_dir)
File "/home/DeepHiC-master/all_parser.py", line 22, in mkdir
os.makedirs(out_dir, exist_ok=True)
File "/home/miniconda3/envs/deephic/lib/python3.6/os.py", line 210, in makedirs
makedirs(head, mode, exist_ok)
File "/home/miniconda3/envs/deephic/lib/python3.6/os.py", line 210, in makedirs
makedirs(head, mode, exist_ok)
File "/home/miniconda3/envs/deephic/lib/python3.6/os.py", line 220, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/DeepHiC'

**Comment by ghost** [comment]
If the previously mentioned methods of obtaining Singularity images are not viable, is there an alternative solution that would be to explore other options for using the 3D Genome Builder tool.

**Comment by pierrepo** [comment]
According to the [README](https://github.com/nservant/HiC-Pro), it is possible to manually install HiC-Pro, but I haven't tried it myself.
